title: "Laravel Boilerplate"
remote_theme: just-the-docs/just-the-docs@main
search_enabled: true
aux_links:
  "Boilerplate on GitHub":
    - "//github.com/sebastienheyd/boilerplate"
plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
color_scheme: blue
